#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url: http://3.84.217.9:8082/artifactory/libs-release/com/web/webApp/1.0-RELEASE/webApp-1.0-RELEASE.war
      dest: /home/ec2-user
      url_username: admin
      url_password: Admin123

  - name: Rename .war Artifact
    command: mv webApp-1.0-RELEASE.war web.war
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: web
      build:
        path: /home/ec2-user
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: rmspavan
     password: P2$$w0rd

    
  - name: Push to docker hub
    docker_image:
      name: web
      repository: rmspavan/web:1.0
      push: yes
      source: local
